site_name: A Blog
site_author: Xiaofeixia
copyright: Copyright © 2025 Xiaofeixia
repo_url: https://github.com/Xiaofeixia2008/blog/

theme:
  name: material
  features:
    - search.highlight
    - search.suggest

markdown_extensions:
  - footnotes
  - md_in_html
  - smarty
  - tables
  - toc:
      permalink: true
      separator: _
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: asterisk
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.blocks.tab
  - pymdownx.caret
  - pymdownx.fancylists
  - pymdownx.highlight:
      linenums: true
  - pymdownx.keys:
      camel_case: true
  - pymdownx.magiclink:
      repo_url_shortener: true
      user: PumpkinJui
      repo: blog
      normalize_issue_symbols: true
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      disable_indented_code_blocks: true
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist
  - pymdownx.tilde
  - mdx_truly_sane_lists

plugins:
  - search
  - offline
  - git-revision-date-localized:
      fallback_to_build_date: true

extra_javascript:
  - path: https://cdn.jsdmirror.com/npm/mermaid@latest/dist/mermaid.esm.min.mjs
    type: module
    async: true
  - path: https://cdn.jsdmirror.com/npm/mathjax@3/es5/tex-chtml-full.js
    defer: true
  - path: scripts/mathjax.js
    defer: true
